# Generated by Django 5.2 on 2025-04-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dosage', models.CharField(max_length=30, blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('morning', models.DecimalField(blank=True, null=True, max_digits=5, decimal_places=2)),
                ('afternoon', models.DecimalField(blank=True, null=True, max_digits=5, decimal_places=2)),
                ('evening', models.DecimalField(blank=True, null=True, max_digits=5, decimal_places=2)),
                ('provider', models.CharField(max_length=30)),
                ('refilled', models.DateField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
